<template>
  <transition
    appear
    name="custom-classes-transition"
    :enter-active-class="hookEnterActive()"
    :leave-active-class="hookLeaveActive()"
  >
    <view
      class="U-exterior"
      v-if="canRender()"
      :hid="hid"
      :clone="clone"
      :style="STYLE"
      :class="CLASS"
    >
      <div class="U-exterior-wrap" :hid="hid" ref="app"></div>
    </view>
  </transition>
</template>
